# _*_ mode: ruby _*_
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configurations
  config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
  config.ssh.insert_key = false
  config.vm.synced_folder ".","/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
      v.memory = 2048
  #    v.linked_clone = true
  end

  # Control server.
  config.vm.define "control" do |app|
    app.vm.hostname = "control.example.com"
    app.vm.network :private_network, ip:"192.168.60.10"
  end



end
