---
- hosts: all
  become: true

  # change hostname
  # change /etc/hosts file
  # sudoers add oracle
  # yum update
  # mount open-vm tools - update fstab
  # install maven
  # install python
  # install oracle 19c prep file
  # iinstall jdk 11
  # unisntall open_jdk
  # create user oracle
  # install ansible


  tasks:
  - name: Change Host name.
    ansible.builtin.hostname:
      name: dev1.lcf.com

  - name: Replace mappings to /etc/hosts.
    ansible.builtin.replace:
      path: /etc/hosts
      regexp: 'base'
      replace: 'dev1'


  roles:
    - { role: tecris.maven, maven_major: 3, maven_version: 3.6.3, maven_home_parent_directory: /opt}

    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: no
      oracle_java_dir_source: '/usr/local/src'
      oracle_java_download_timeout: 60
      oracle_java_rpm_filename: 'jdk-11.0.3_linux-x64_bin.rpm'
      oracle_java_home: '/usr/java/default'
      oracle_java_os_supported: yes
     # oracle_java_rpm_url: 'https://download.oracle.com/otn/java/jdk/11.0.3+12/37f5e150db5247ab9333b11c1dddcd30/jdk-11.0.3_linux-x64_bin.rpm'
      oracle_java_rpm_url: file:///Users/joe/Downloads/jdk-11.0.6_linux-x64_bin.rpm 
      oracle_java_rpm_validate_certs: yes
      oracle_java_set_as_default: yes
      oracle_java_version_string: 11.0.3
