---
- hosts: dev1.lcf.com
  remote_user: oracle

  #sudo: yes
  vars:
    download_url: "file:///Users/joe/Downloads/jdk-11.0.6_linux-x64_bin.rpm"
    download_file_src: "/Users/joe/Downloads/jdk-11.0.6_linux-x64_bin.rpm"
    download_folder: /opt
    java_name: "{{download_folder}}/jdk-11.0.6"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"

  tasks:
  # - name: Download Java
  #   command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

  # - name: Download file from a file path
  #   get_url:
  #     url: file:///Users/joe/Downloads/jdk-11.0.6_linux-x64_bin.rpm
  #     dest: "{{java_archive}}"

  - name: Copy rpm file to server
    copy:
     src: /Users/joe/Downloads/jdk-11.0.6_linux-x64_bin.rpm
     dest: /tmp/rpm

  # - name: Install package.
  #   yum:
  #     name: /home/oracle/Downloads/jdk-11.0.6_linux-x64_bin.rpm
  #     state: present
  #     become: true

  - name: Installed the rpm files
    shell: yum localinstall *.rpm -y
    args:
      chdir: /tmp/rpm
    become: true
          # - name: Unpack archive
  #   command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}