---
- hosts: ocidev
  gather_facts: false
  become: true
  vars_files:
    vars/main_vars.yml
  handlers:
    - import_tasks: handlers.yml

  tasks:

    - name: Create group and user.
      import_tasks: create_user.yml
      tags: done

    - name: install git
      yum:
        name: git
        state: present
      tags: done
  
    - name: install python3.
      yum:
        name: python3
        state: present
      tags: done

    - name: remove open jdk.
      yum:
        name: java-1*
        state: absent
      tags: done

    - name: install jdk and intellij and jmeter.
      import_tasks: install_stuff.yml
      tags: done

# install gnome
    - name: import Gnome tasks.
      import_tasks: install_gnome.yml
      tags: done