---
- hosts: all
  gather_facts: false
  become: true
  vars_files:
    vars/main_vars.yml
  tasks:
    - name: update yum.
      yum:
        name: "*"
        state: latest

    - name: create Group
      group:
        name: oracle
        state: present

    - name: add user.
      user:
        name: "{{ create_user }}"
        group: "{{ create_group }}"
        createhome: true
        password: "{{ vaulted_password | password_hash('sha512') }}"
        system: true

    - name: add Oracle to sudoers file.
      lineinfile:
        path: /etc/sudoers
        line: "oracle  ALL=(ALL) NOPASSWD:ALL"        

    - name: install git
      yum:
        name: git
        state: present
      
    - name: remove open jdk.
      yum:
        name: java*
        state: absent
