---
- hosts: ocidev
  gather_facts: false
  become: true
  vars_files:
    vars/main_vars.yml
  handlers:
    - import_tasks: handlers.yml

  tasks:

    - name: Create group and user.
      import_tasks: create_user.yml

    - name: install git
      yum:
        name: git
        state: present

    - name: remove open jdk.
      yum:
        name: java*
        state: absent

# install gnome
    - name: import Gnome tasks.
      import_tasks: install_gnome.yml
