---
- hosts: all
  gather_facts: false
  become: true
  vars_files:
    vars/main_vars.yml
  tasks:
    - name: update yum.
      yum:
        name: "*"
        state: latest
      

    - name: add Oracle to sudoers file.
      lineinfile:
        path: /etc/sudoers
        line: "oracle  ALL=(ALL) NOPASSWD:ALL"   
        state: present

    - name: install git
      yum:
        name: git
        state: present

    - name: remove open jdk.
      yum:
        name: java*
        state: absent

    - name: Install the 'Gnome desktop' environment group.
        yum:
          name:
            - "@GNOME"
            - "@X Window System"
            # - "@^gnome-desktop-environment"
            # - "@development-tools"
            # - "@^gnome-desktop-environment"
          state: latest

      - name: Change default target to graphical.target.
        file:
          src: /usr/lib/systemd/system/graphical.target
          dest: /etc/systemd/system/default.target
          state: link

      - name: start the gnome service.
        systemd:
          name: "graphical.target"
          state: started