galaxy_info:
  author: Vincent Rischmann
  description: Backend engineer

  license: MIT

  min_ansible_version: 2.0

  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
  - name: Fedora
    versions:
      - all
  - name: Debian
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  - name: ArchLinux
    versions:
      - all
  - name: MacOSX
    versions:
      - all

  galaxy_tags:
    - minikube
    - kubernetes

dependencies: []
