---
- hosts: all
  become: yes

  tasks:
  - name: Ensure chrony (for time sycnh) is installed.
    yum:
      name: chrony
      state: present

  - name: Ensure chrony is running
    service:
      name: chronyd
      state: started
      enabled: yes
