---
- hosts: mylocalhost
  become: true
  vars:
     jenkins_http_port: 8090
#      - update yum, new user: oracle, add to sudoer, git, curl, python3, python-pip3, java jdk 11 + env vars, derby db, jmeter, intellij,
#      - maven, docker, minikube, kubectl, jenkins, clone repo for course, labs files

  roles:
 
     - role: update_distro
#       tags: do 
     - role: change_hostinfo

     - role: create_admin_user
#       tags: do

     - role: add_linux_support
#       tags: do

     - role: create_java_development
 #       tags: do


     - role: gantsign.maven
#       tags: do

 #    - role: install_docker
#       tags: do

#  - role: vrischmann.minikube
     - role: install_minikube


     # - role: change_java_version
     #   tags: do 

     # - role: geerlingguy.jenkins
     - role: install_jenkins


     - role: update_distro
 

  post_tasks:
     - name: reboot system.
       command: sudo reboot
     
      # - role: install_course_files



      # reboot at end

 
 #    - role: install_course_files (indludes clone repo, set hostname to include dukelabs.org)


